### ISSUE TITLE
Old-style class defined

### ISSUE THREAD

**Issue by NitescuLucian** [WangYihang/SourceLeakHacker#3]
```
7
8 screenLock = threading.Semaphore(value=1)
9
10 class ColorPrinter:
11     @staticmethod
12     def print_red_text(content):
```
In regards to line 10.

Why is this an issue?
In Python 2.x, old-style classes are defined by not inheriting from a base class or by inheriting from other old-style classes. New-style classes are defined by inheriting from class object or from other new-style classes.
Python 3.x supports only new-style classes; if no base class is specified on a class definition, the class implicitly inherits from object.
It is recommended to define only new-style classes, because they are properly integrated into Python's type system. 

https://www.python.org/doc/newstyle/

Not mandatory and with no relevant improvement to the master but keep in mind for future 👍

**Comment by WangYihang** [comment]
Thanks again for the advice, I will go and see the official documentation, thanks a lot! 💯
