### ISSUE TITLE
SSL报错

### ISSUE THREAD

**Issue by LL-MF** [WangYihang/SourceLeakHacker#6]
请问有中文手册吗；还有爬虫模块SSL没处理好

**Comment by WangYihang** [comment]
1. 没有中文手册。
2. 可以麻烦您提供一下没处理好的具体细节吗？比如报错信息或者测试用例。
@LL-MF

**Comment by LL-MF** [comment]
(Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_proce ssl的证书错误

**Comment by WangYihang** [comment]
@LL-MF , ssl 问题已解决，感谢反馈。
